export const dashboardCard = [
    {
        title: "Total Sales Order",
        total: "4,152,783,787",
        color: "text-blue-600",
        border: "border-blue-600",
    },
    {
        title: "Total Purchase Order",
        total: "4,152,783,787",
        color: "text-green-600",
        border: "border-green-600",
    },
    {
        title: "Total Penjualan Limbah",
        total: "4,152,783,787",
        color: "text-teal-600",
        border: "border-teal-600",
    },
    {
        title: "Gross Pendapatan",
        total: "4,152,783,787",
        color: "#60af00",
        border: "border-yellow-600",
    },
];

export const dataTable = [
    {
        "id": 1,
        "name": "Torrey",
        "email": "tgateshill0@biblegateway.com",
        "phone": "754-376-3236"
    }, {
        "id": 2,
        "name": "Nathanil",
        "email": "nselburn1@japanpost.jp",
        "phone": "358-620-3884"
    }, {
        "id": 3,
        "name": "Jinny",
        "email": "jmaes2@elpais.com",
        "phone": "877-630-6858"
    }, {
        "id": 4,
        "name": "Illa",
        "email": "iohanvey3@plala.or.jp",
        "phone": "685-997-2763"
    }, {
        "id": 5,
        "name": "Emylee",
        "email": "estonebanks4@cnn.com",
        "phone": "353-943-8846"
    }, {
        "id": 6,
        "name": "Scarlet",
        "email": "slightbown5@e-recht24.de",
        "phone": "241-695-4045"
    }, {
        "id": 7,
        "name": "Maxim",
        "email": "mpischoff6@squarespace.com",
        "phone": "532-149-9603"
    }, {
        "id": 8,
        "name": "Augustus",
        "email": "adecourtney7@phoca.cz",
        "phone": "761-993-3556"
    }, {
        "id": 9,
        "name": "Ursula",
        "email": "uthurlborn8@pcworld.com",
        "phone": "786-415-2232"
    }, {
        "id": 10,
        "name": "Perceval",
        "email": "pbuxcy9@goo.gl",
        "phone": "409-821-0839"
    }, {
        "id": 11,
        "name": "Jana",
        "email": "jmcgormana@rambler.ru",
        "phone": "575-386-7136"
    }, {
        "id": 12,
        "name": "Marshal",
        "email": "mdurrellb@howstuffworks.com",
        "phone": "933-267-9653"
    }, {
        "id": 13,
        "name": "Dino",
        "email": "dcandlinc@google.ca",
        "phone": "435-934-3896"
    }, {
        "id": 14,
        "name": "Fanny",
        "email": "ftellingd@slideshare.net",
        "phone": "624-521-3374"
    }, {
        "id": 15,
        "name": "Olvan",
        "email": "ofairlawe@last.fm",
        "phone": "731-462-7524"
    }, {
        "id": 16,
        "name": "Cassey",
        "email": "cmckendryf@dailymotion.com",
        "phone": "672-570-7511"
    }, {
        "id": 17,
        "name": "Dino",
        "email": "dcastellettig@zimbio.com",
        "phone": "760-748-5108"
    }, {
        "id": 18,
        "name": "Travis",
        "email": "tgianielloh@nyu.edu",
        "phone": "323-756-9684"
    }, {
        "id": 19,
        "name": "Craig",
        "email": "ckryszkai@devhub.com",
        "phone": "572-896-5870"
    }, {
        "id": 20,
        "name": "Janaye",
        "email": "jconnikiej@hud.gov",
        "phone": "466-960-8731"
    }, {
        "id": 21,
        "name": "Lexine",
        "email": "lbainbridgek@walmart.com",
        "phone": "996-304-1056"
    }, {
        "id": 22,
        "name": "Denna",
        "email": "dmanonl@xrea.com",
        "phone": "169-614-7663"
    }, {
        "id": 23,
        "name": "Bianca",
        "email": "bwalkinshawm@squarespace.com",
        "phone": "637-624-6692"
    }, {
        "id": 24,
        "name": "Maxie",
        "email": "mkesonn@mit.edu",
        "phone": "295-818-6747"
    }, {
        "id": 25,
        "name": "Constantine",
        "email": "ccookleyo@latimes.com",
        "phone": "558-125-9405"
    }, {
        "id": 26,
        "name": "Erl",
        "email": "eeckfordp@utexas.edu",
        "phone": "768-849-0786"
    }, {
        "id": 27,
        "name": "Harmonie",
        "email": "hlecountq@economist.com",
        "phone": "480-702-7450"
    }, {
        "id": 28,
        "name": "Harley",
        "email": "hnewisr@china.com.cn",
        "phone": "402-215-9487"
    }, {
        "id": 29,
        "name": "Celestyna",
        "email": "cbrokenshaws@twitpic.com",
        "phone": "100-147-9009"
    }, {
        "id": 30,
        "name": "Lindsay",
        "email": "linglesont@nydailynews.com",
        "phone": "518-587-7260"
    }, {
        "id": 31,
        "name": "Trescha",
        "email": "tstycheu@ustream.tv",
        "phone": "863-332-8582"
    }, {
        "id": 32,
        "name": "Oneida",
        "email": "ojanseyv@cafepress.com",
        "phone": "644-345-1125"
    }, {
        "id": 33,
        "name": "Rudyard",
        "email": "rtarpeyw@mail.ru",
        "phone": "389-182-1499"
    }, {
        "id": 34,
        "name": "Tammara",
        "email": "tsommerlandx@csmonitor.com",
        "phone": "933-536-3994"
    }, {
        "id": 35,
        "name": "Albert",
        "email": "agoszy@amazonaws.com",
        "phone": "150-250-4299"
    }, {
        "id": 36,
        "name": "Rolf",
        "email": "rbostockz@bloglovin.com",
        "phone": "655-990-0224"
    }
]